### ISSUE TITLE
create comment text object

### ISSUE THREAD

**Issue by redguardtoo** [redguardtoo/evil-nerd-commenter#63]
as title. use font-face, should be general enough, support different major-mode

**Comment by Somelauw** [comment]
A comment text object is provided by [evil-cleverparens-text-objects](https://github.com/luxbock/evil-cleverparens/blob/master/evil-cleverparens-text-objects.el).

**Comment by braham-snyder** [comment]
`evil-cleverparens`'s comment text objects are very convenient (and I'm really glad they exist), but they seem tangential to the rest of the package.

This isn't at all a deal-breaker in my eyes, but I think those text objects might be quite a bit more beneficial in a more appropriate package (like `evil-nerd-commenter`): e.g., it would seem like overkill to me for `evil-cleverparens` to bother offering configuration for its `in-comment` object to variously exclude all of the comment prefixes of the selected comment (its current behavior) vs. leaving only one comment prefix character; or to toggle inclusion of one additional newline (for non-in-line comments) with its `a-comment` object.

**Comment by redguardtoo** [comment]
@braham-snyder what languages you are using? Can you show me more examples?

I think I can do much better.

**Comment by braham-snyder** [comment]
`evil-change` `evil-cp-inner-comment` from the end of this sentence (`|` is point):

```
  ;; Fusce suscipit, wisi nec facilisis facilisis, est dui fermentum leo, quis
  ;; tempor ligula erat quis odio|.
```
leaves me<sup>1</sup>:
```
  ;; |
  ;;
```
when, instead, I'd guess that many if not most would prefer:
```
  ;; |
```

Additonally, `evil-cp-a-comment` really ought to automatically re-indent when used with `evil-change`, as `evil-a-paragraph` and `evil-line` do--that is, `evil-change` `a-comment` from the first excerpt above leaves me:
```
|
```
when it ought to leave:
```
  |
```

Regarding the inclusion of an additional newline in the text object, dwim behavior as `evil-line` exhibits would be ideal, I think--for example, `evil-delete` of `a-comment` here:
```
;; foo|
bar(qux)
```
ought to leave only:
```
|bar(qux)
```
instead of:
```
|
bar(qux)
```
but `evil-change` `a-comment` from the same place ought to result in the latter.

I would be surprised if inclusion of comment text objects in `evil-nerd-commenter` didn't result in additional improvements to their behavior, considering many more people would likely notice and use them.

<sup>1</sup> Actually, at the moment, I'm left with something like this instead, but there's a decent chance this is due to my configuration and not `evil-cleverparens` (currently, I only use `evil-cleverparens`'s `a-comment` in light of the behavior above):
```
  ;; |ilisis facilisis, est dui fermentum leo, quis
  ;; .
```

...and I'm also seeing, now, that `evil-delete` `evil-cp-inner-comment` on:
```
;; |foo
```
leaves me:
```
;; o
```
unless I use:
```
(setq evil-move-beyond-eol t)
(setq evil-move-cursor-back nil)
```

**Comment by redguardtoo** [comment]
a61f920 commenter text objext finished (Chen Bin)
