### ISSUE TITLE
"sexy" mode

### ISSUE THREAD

**Issue by hoopes** [redguardtoo/evil-nerd-commenter#65]
Hi (my apologies if this is not the right place to ask questions - I can close and reopen in stack overflow if desired),

I'm a vimmer coming over to spacemacs. I used to use nerdcommenter, so i was happy to see this port in emacs, and auto-included in spacemacs.

In vim (let's use javascript as an example), let's pretend I used visual mode to highlight a couple lines. I could use `<Leader>cc` to comment them with `//`, or `<Leader>cs` to do "sexy" comments (wishing for a better name...) where it would surround the highlighted lines with `/** */`. 

Is this possible with evil-nerd-commenter? I can't seem to find anything in the emacs commands to support it.

Thanks very much for any advice/replies.

**Comment by redguardtoo** [comment]
It's certainly doable. But I need manually implement the comment function instead of outsourced the function to Emacs API `comment-region`. Currently my code has less line than vim matchit (I read vim implementation line by line). I'd rather keep this way.

You can write your own plugin to do the job. Check https://github.com/mooz/js-doc for the sample.
